<?php
$cidade = " - Peruibe - SP";
$anunciantesPeruibe = [
	[
		        'nome' => 'Mega Imvóveis Peruíbe',
		   'descricao' => 'Empresa da área imobiliária',
		    'endereco' => 'Av. Pe. Anchieta, 5.470, Pq. Turistico, Peruibe, SP',
		   'telefones' => '(13)99729-1061 / (13)3458-4730',
		'categoria_id' => '',
			'conjunto' => ['imovel'],
			'palavras' => [],
		        'site' => 'http://www.megaimoveisperuibe.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Perita Acessoria Contábil',
		   'descricao' => 'Acessoria e serviços de contabilidade',
		    'endereco' => 'Av. 24 de Dezembro, 136',
		   'telefones' => '(13)3455-7595 / Fax:(13)3455-7439',
		'categoria_id' => '',
			'conjunto' => ['contabilidade'],
			'palavras' => [],
		        'site' => 'http://www.perita.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Super Car Centro Automotivo',
		   'descricao' => 'Trabalhamos com: motor, câmbio, suspensão, freios, elétrica, injeção eletrônica, limpeza de bicos, limpeza do sistema de arrefecimento, troca de óleo, alinhamento, balanceamento, borracharia',
		    'endereco' => 'Estrada Armando Cunha, 70, Parque do Treve, Peruibe, SP',
		   'telefones' => '(13)3458-3412 / 99626-5604',
		'categoria_id' => '',
			'conjunto' => ['centro automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Madeireira Marimar',
		   'descricao' => 'Trabalhamos com: madeiras brutas e aparelhadas, madeiras para telhados, portas, batentes, guarnições, forro de PVC. Temos completa linha de telhas em especial ESMALTADAS.',
		    'endereco' => 'Est. Armando Cunha, 40, Vl. Erminda (próximo ao viaduto da entrada de Peruibe), Peruibe, SP',
		   'telefones' => '(13)3458-2992 / 99779-1797 / ID: 125*52753 - Nextel: 7821-3857',
		'categoria_id' => '',
			'conjunto' => ['madeira'],
			'palavras' => [],
		        'site' => 'http://www.marcenariamarimar.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'King Streets',
		   'descricao' => 'Loja moda masculina e feminina, trabalha com as marcas: Oakley, Lacoste, Paulo Ralph Lauren, Osklen, Reserva, AX',
		    'endereco' => 'Av. Pe. Leonardo Nunes, 1150 - Centro - Peruibe - SP',
		   'telefones' => 'Fone/WhatsApp: (13)99-716-9839',
		'categoria_id' => '',
			'conjunto' => ['roupa'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Academia Dan Fitness',
		   'descricao' => 'Diversas modalidades esportivas',
		    'endereco' => 'Av. São João, 150 - Centro - Peruibe - SP',
		   'telefones' => '(13)3455-8735',
		'categoria_id' => '',
			'conjunto' => ['academia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Casa de Carnes e Mercearia D'Aville",
		   'descricao' => 'Aceitamos encomendas e entregamos a domicílio',
		    'endereco' => "Rua Luiz de Paula, 11 - loja 02 - Park D'aville - Peruibe - SP",
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['acougue'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Serra do Jaí distribuidora de água',
		   'descricao' => 'Distribuidora de água',
		    'endereco' => 'Av. Pe. Anchieta, 4489 - loja 02 - Três Marias - Peruibe - SP',
		   'telefones' => '(13)3458-2121 / (13)99-667-5799',
		'categoria_id' => '',
			'conjunto' => ['agua'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Juréia Pesca',
		   'descricao' => 'Tudo para sua pescaria',
		    'endereco' => 'Av. Pe. Anchieta, 3322 - São João Batista - Peruibe - SP',
		   'telefones' => '(13) 3455-1410',
		'categoria_id' => '',
			'conjunto' => ['pescaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Português Locação de Andaimes',
		   'descricao' => 'Locação de andaimes para obras.',
		    'endereco' => 'Av. Vereador Vitor Caetano dos Santos, 59 - Jd. Brasil - Peruibe - SP',
		   'telefones' => '(13) 99757-7545 / 3453-2727',
		'categoria_id' => '',
			'conjunto' => ['andaime'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Gonçalves Máquinas',
		   'descricao' => 'Manutenção de ferramentas e equipamentos a gasolina. Peças e serviços.',
		    'endereco' => 'Av. Marginal, 315 - B. dos Prados - Peruibe - SP',
		   'telefones' => '(13)99634-5255 / (13)99625-8237 / Loja: (13)99615-8096',
		'categoria_id' => '',
			'conjunto' => ['manutencao maquina'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Denise Centro de Formação de Condutores',
		   'descricao' => 'Carteira de motorista para carros e motos',
		    'endereco' => 'Av. 24 de Dezembro, 733 - Estação - Peruibe - SP',
		   'telefones' => '(13)3453-5858',
		'categoria_id' => '',
			'conjunto' => ['auto escola'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'DPeruibe Centro de Formação de Condutores',
		   'descricao' => 'Cursos de: Transporte coletivo de passageiros, transporte de cargas perigosas, transporte escola, transporte de emergência, primeira habilitação, renovação de habilitação, reciclagem de condutores, moto taxi, moto frete',
		    'endereco' => 'Av. Domingo da Costa Grimaldi, 212 - loja 01 - Centro - Peruibe',
		   'telefones' => '(13)3455-1074 / (13)99614-0309(whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['auto escola'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Auto Elétrico Thiaguinho',
		   'descricao' => 'Especializado em importados. Reparo em módulo de injeção, airbag, ABS, ar condicionado.',
		    'endereco' => 'Av. Pe. Anchieta, 6532 - Est. São José - Peruibe - SP',
		   'telefones' => '(13)3458-3367 / (13)99654-2729 (whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['auto eletrica'],
			'palavras' => [],
		        'site' => 'http://www.autoeletricothiaguinho.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Auto Peças e Serviços',
		   'descricao' => 'Auto peças em geral',
		    'endereco' => 'Rua Pietro Bertoline, 1002 - Jd. Beira Mar (esquina com a Av. Marginal Fepasa próx. a Madeireira ANPP) - Peruibe - SP',
		   'telefones' => '(13)3456-1783 / nextel: 662*18791',
		'categoria_id' => '',
		 	'conjunto' => ['auto pecas'],
		 	'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Bar do Marcão',
		   'descricao' => 'A cerveja mais gelada da cidade.',
		    'endereco' => 'Av. Vereador João Bechir, 365 - Estação - Peruibe - SP',
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['bar'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Tô Limpinho Banho e Tosa',
		   'descricao' => 'Prezamos pelo bem estar e higiene do seu amiguinho. Temos pacotes promocionais de banho',
		    'endereco' => 'Av. Pref. Gheorghe Popescu, 20 - Continental - Peruibe - SP',
		   'telefones' => '(13)3458-4588 / 98133-1967(whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['tosa'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Espaço Perfeito Berçario e Educação Infantil',
		   'descricao' => 'Berçario e Educação Infantil - Uniter',
		    'endereco' => 'Rua Dr. Braz Belmont, 1015 - Bal. Flórida - Peruibe - SP',
		   'telefones' => '(13)3454-1204',
		'categoria_id' => '',
			'conjunto' => ['bercario'],
			'palavras' => [],
		        'site' => 'http://www.espacoperfeito.com',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Botequim Sabor do Brasil',
		   'descricao' => 'Almoço e Janta de segunda à sexta. Pizzas e música ao vivo aos finais de semana.',
		    'endereco' => 'Av. São Domingos esquina com a Pe. Anchieta, 390 - Arpoador - Peruibe - SP',
		   'telefones' => '(13)3455-3229',
		'categoria_id' => '',
			'conjunto' => ['bercario'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Bazar e Papelaria Juju',
		   'descricao' => 'Pipas e todos os tipos de acessórios, presentes e brinquedos, controles remoto para tv e dvd, xerox e fax, acessórios para celular, variedades em geral',
		    'endereco' => 'Av. Luciano de Bona, 3001 - São João Batista II - Peruibe - SP',
		   'telefones' => '(13)3455-1387',
		'categoria_id' => '',
			'conjunto' => ['papelaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Toreli Papelaria',
		   'descricao' => 'Presentes, xerox, impressão, email, pesquisa, plastificação, encadernação, informática',
		    'endereco' => 'Rua Reinaldo Barcelos Pereira, 10 - loja 04 - Vila Romar - Peruibe - SP',
		   'telefones' => '(13)99759-6913',
		'categoria_id' => '',
			'conjunto' => ['papelaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'KLG Borracharia & Baterias',
		   'descricao' => 'Baterias e serviço de borracharia',
		    'endereco' => 'Av. Luciano de Bona, 2621 - Jd. Ribamar - Peruibe - SP',
		   'telefones' => '(13)99610-2035 / 97415-6520',
		'categoria_id' => '',
			'conjunto' => ['borracharia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Black White cabeleireiros unissex',
		   'descricao' => 'Escovas, Apliques, Unha',
		    'endereco' => 'Av. Pe. Leonardo Nunes, 427 - loja 2 - Centro - Peruibe - SP',
		   'telefones' => '(13)3455-5654 / 3455-5859 / 997405-9904 (Miguel)',
		'categoria_id' => '',
			'conjunto' => ['cabeleireiro'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Vivi Hair cabeleireiros',
		   'descricao' => 'Escova, Penteados, Maquiagem, Químicas em geral',
		    'endereco' => 'Rua Taquaritinga, 48 - loja B - Centro - Peruibe - SP',
		   'telefones' => '(13)3453-1735 / 99728-2627(whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['cabeleireiro'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Tira Entulho Obra Limpa',
		   'descricao' => 'Aluguel de caçambas, remoção de entulhos',
		    'endereco' => '',
		   'telefones' => '(13)3455-2030 / vivo:(13)99713-9276 / tim:(13)98154-8443',
		'categoria_id' => '',
			'conjunto' => ['entulho'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Fashion Feet',
		   'descricao' => 'Sapatos, sapatilhas, bolsas, acessórios, modelos exclusivos',
		    'endereco' => 'Av. Domingos da Costa Grimaldi, 54 - loja 06 - Centro - Peruibe - SP',
		   'telefones' => '(13)3454-1841',
		'categoria_id' => '',
			'conjunto' => ['loja sapato'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Toltec - Toldos e coberturas',
		   'descricao' => "Persianas verticais e horizontais, holl'on, romanas, duovision e painel, toldos ",
		    'endereco' => 'Av. Pe. Anchieta, 9133 - Ruinas - Peruibe - SP',
		   'telefones' => '(13)99658-3535(whatsapp) / (13)99768-6898',
		'categoria_id' => '',
			'conjunto' => ['toldo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Kebinha Calhas',
		   'descricao' => 'Calhas, rufos, condutores, exaustores, eólicos',
		    'endereco' => 'Av. Tancredo Neves, 980 - Jd. Brasil - Peruibe - SP',
		   'telefones' => '(13)99756-5748',
		'categoria_id' => '',
			'conjunto' => ['calha'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Nordestão Casa do Norte',
		   'descricao' => 'Grãos, farinhas, bolvilhos, doces típicos',
		    'endereco' => 'Av. Luciano de Bona, 2247 - Jangada - Peruibe - SP',
		   'telefones' => '(13)99726-9997',
		'categoria_id' => '',
			'conjunto' => ['casa norte'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Casa do Norte Novo Horizonte',
		   'descricao' => 'Carne seca, farinha de mandioca, manteiga, ingredientes p/ feijoada, doces, biscoitos, bolachas',
		    'endereco' => 'Rua Rosa G. Fortuna, 360 - Estação - Peruibe - SP',
		   'telefones' => '(13)3453-5652',
		'categoria_id' => '',
			'conjunto' => ['casa norte'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Spy - Segurança',
		   'descricao' => 'câmeras de segurança, instalação e manutenção',
		    'endereco' => 'Av. São João, 490 - loja 6 (Galeria Afinidades) - Centro - Peruibe - SP',
		   'telefones' => '(13)3455-4405 / (13)99759-1667 (whatsApp)',
		'categoria_id' => '',
			'conjunto' => ['seguranca'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Casa da Ração JN',
		   'descricao' => 'Rações em geral, insumos, medicamentos, acessórios, pássaros',
		    'endereco' => 'Rua Marília, 1344 - Caraguava - Peruibe - SP',
		   'telefones' => '(13)3454-5583 / (13)99629-3839(whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['petshop'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Davi Rações',
		   'descricao' => 'Rações, brinquedos, acessórios, medicamentos, banho e tosa. Disk ração',
		    'endereco' => 'Av. Luciano de Bona, 2551 - Ribamar - Peruibe - SP',
		   'telefones' => '(13)3455-2096',
		'categoria_id' => '',
			'conjunto' => ['petshop'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Master Cell',
		   'descricao' => 'Venda e manutenção de celulares e tablets',
		    'endereco' => 'Rua dos Pescadores, 14 - loja 1',
		   'telefones' => '(13)3453-6157 / (13)99676-6486(whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['loja celular'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Kirobe automotivo',
		   'descricao' => 'Alinhamento, balanceamento, freios, troca de óleo, suspensão',
		    'endereco' => 'Av. Luciano de Bona, 1901 - Vila Romar - Peruibe',
		   'telefones' => '(13)3453-4991 / (13)99763-8482 (whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['centro automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Maxi's Pneus",
		   'descricao' => 'Centro automotivo',
		    'endereco' => 'Av. Luciano de Bona, 2455 - Ribamar - Peruibe - SP',
		   'telefones' => '(13)3455-7953',
		'categoria_id' => '',
			'conjunto' => ['centro automotivo'],
			'palavras' => [],
		        'site' => 'http://www.maxispneus.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Aline Cestas de Café da Manhã',
		   'descricao' => 'Cestas de café da manhã, cestas de chocolate, cestas românticas, Almofadas personalizadas com foto, canecas personalizdas com foto, relógios de parede personalizados, coração de bombom, caixa de guloseimas, bandeja de vinho com taças, pelúcias',
		    'endereco' => '',
		   'telefones' => '(13)99611-0801',
		    'conjunto' => ['cesta cafe'],
			'palavras' => [],
		'categoria_id' => '',
		        'site' => 'http://www.facebook.com/cestas-peruibe',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Arcanjo's Chaveiro",
		   'descricao' => 'Especializado em chaves codificadas',
		    'endereco' => 'Av. São João, 602 - Centro - Peruibe - SP',
		   'telefones' => '0800-772-5558',
		'categoria_id' => '',
			'conjunto' => ['chaveiro'],
			'palavras' => [],
		        'site' => 'http://www.chaveiroarcanjos.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Centro Esportivo Peruibão',
		   'descricao' => 'Locação para eventos, aniversários, confraternização e casamentos. Quadra de grama sintética.',
		    'endereco' => 'Rua Barão de Mauá, 87 - Centro'.$cidade,
		   'telefones' => '(13)3453-4834',
		'categoria_id' => '',
			'conjunto' => ['centro esportivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Parkbol - Futebol Society Peruibe',
		   'descricao' => 'Locação de quadras, Espaço para eventos, Escolinha de futebol',
		    'endereco' => "Rua Augusto Lima, 101 - Park D'aville".$cidade,
		   'telefones' => '(13)99-734-0626',
		'categoria_id' => '',
			'conjunto' => ['centro esportivo'],
			'palavras' => [],
		        'site' => 'http://www.parkbol.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Churrascaria Nova Tradição',
		   'descricao' => 'Rodízio, sef service, marmitex, churrasco para viagem',
		    'endereco' => 'Av. Padre Anchieta, 7258 - Josedy'.$cidade,
		   'telefones' => '(13)3456-3462',
		'categoria_id' => '',
			'conjunto' => ['churrascaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Churrascaria Nonohay',
		   'descricao' => 'Qualidade no atendimento',
		    'endereco' => 'Travessa Profa Terezinha Rodrigues Kalil, 1085'.$cidade,
		   'telefones' => '(13)3455-9741',
		'categoria_id' => '',
			'conjunto' => ['churrascaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Delícias de Minas',
		   'descricao' => 'Linguiças especiais, doces, queijos, cachaças',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)99-623-4105',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['linguiça', 'doce', 'queijo', 'cachaca', 'linguiças', 'doces', 'queijos', 'cachacas'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'KR Componentes',
		   'descricao' => 'Componentes eletrônicos, instrumentos musicais, controles remotos, conversores HDMI / VGA / RCA',
		    'endereco' => 'Av. Pe. Anchieta, 5609 - Sala 02 - Oassís'.$cidade,
		   'telefones' => '(13)3454-1414',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['fonte', 'telefone', 'falante', 'tweeter', 'driver', 'corneta', 'bateria', 'camera', 'plug', 'conector', 'fio', 'cabo', 'fontes', 'telefones', 'falantes', 'tweeters', 'drivers', 'cornetas', 'baterias', 'cameras', 'plugs', 'conectores', 'fios', 'cabos'], 
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Compressores Peruíbe',
		   'descricao' => 'Consertos e reformas de compressores, compra, vende e troca compressores de todas as marcas',
		    'endereco' => 'Av. Tancredo A. Neves, 1095 - Jardim Brasil'.$cidade,
		   'telefones' => '(13)99-649-0201 / (11)99-893-2705',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['compra', 'venda', 'troca', 'compressor', 'conserta', 'repara', 'arrauma', 'compressores', 'consertos', 'reparos', 'reparo'],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Quiosque Itiban',
		   'descricao' => 'Comida japonesa de qualidade. Alguns pratos: Rice cury, yakissoba, Hot Holl, Temaki, Uramaki, tempurá, hossomaki, sobá, makizushi',
		    'endereco' => 'Praça Ambrósio Baldin, Box 81 - Centro'.$cidade,
		   'telefones' => '(13)99-625-8513',
		'categoria_id' => '',
			'conjunto' => ['comida japonesa'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Assis da Conceição Corretor de Imóveis',
		   'descricao' => 'Imóveis para aluguel e venda',
		    'endereco' => 'Ab. Pe. Anchieta, 3783 - Nova Peruibe'.$cidade,
		   'telefones' => '(13)3454-2030 / (13)99-773-3998',
		'categoria_id' => '',
			'conjunto' => ['imovel'],
			'palavras' => [],
		        'site' => 'http://www.assisdaconceicaocorretordeimoveis.com.br',
		  'prioridade' => '5',
	],

	[
		        'nome' => "Martha's Buffet",
		   'descricao' => 'Organização, realização, decoração e serviço completo de buffet. Locação de materiais para festa. Atendemos outras localidades',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)99-701-4414 / (11)98-300-7035',
		'categoria_id' => '',
			'conjunto' => ['buffet'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Super Dedetizadora',
		   'descricao' => "Desinsetização, desratização, descupinização, limpeza de caixa d'agua",
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)99-744-6636 (whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['dedetizadora'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Drogaria Nova Kalu',
		   'descricao' => 'Farmácia credenciada como farmácia popular',
		    'endereco' => 'Av. 24 de Dezembro, 597 - Estação'.$cidade,
		   'telefones' => '(13)3453-5703',
		'categoria_id' => '',
			'conjunto' => ['farmacia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Consultório Odontológico Dra. Patrícia',
		   'descricao' => 'Consultório dentário',
		    'endereco' => 'Av. São João, 453 - sala B - Centro'.$cidade,
		   'telefones' => '(13)3455-8988',
		'categoria_id' => '',
			'conjunto' => ['dentista'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Embalamil',
		   'descricao' => 'Embalagens descartáveis',
		    'endereco' => 'Rua Santos Dumont, 169 - Centro'.$cidade,
		   'telefones' => '(13)3455-8852',
		'categoria_id' => '',
			'conjunto' => ['descartavel'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Esquadrias Albino',
		   'descricao' => 'Tudo em alumínio, box, janelas, vidro temperado, sacada, toldo de policarbonato',
		    'endereco' => 'Av. Pe. Anchieta, 4.300 - Nova Peruibe'.$cidade,
		   'telefones' => '(13)3454-1672 / (13)99-107-7236 / (13) 99-727-6691',
		'categoria_id' => '',
			'conjunto' => ['serralheria', 'vidracaria', 'toldo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => '3D Ferragens',
		   'descricao' => 'Elétrica, hidráulica e parafusos',
		    'endereco' => 'Av. Luciano de Bona, 1721 - Lj. 02'.$cidade,
		   'telefones' => '(13)3454-1640',
		'categoria_id' => '',
			'conjunto' => ['ferragem'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Recuperadora Pica Pau',
		   'descricao' => 'Funilaria e pintura',
		    'endereco' => 'Rua Martim Afonso, 23 - Vila Romar'.$cidade,
		   'telefones' => '(13)3453-3699 / (13)97-406-9733',
		'categoria_id' => '',
			'conjunto' => ['funilaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Empório da Fogazza Esfirra Delivey',
		   'descricao' => 'Fogazza, pastel, porção, kit salgado, kit salgado, esfirras, bebidas. Aberto todos os dias das 18:00 às 23:30 hrs',
		    'endereco' => 'Rua Almirante Barroso, 515'.$cidade,
		   'telefones' => '(13)3453-6507/(13)3453-6467/(13)99-717-9180 (vivo)',
		'categoria_id' => '',
			'conjunto' => ['esfirraria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Juja Fisioterapia',
		   'descricao' => 'Treino funcional, pilates, quiropraxia, estética, nutrição',
		    'endereco' => 'Rua Caetano Moratori, 297 - Centro'.$cidade,
		   'telefones' => '(13)3455-5568',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['treino', 'funcional', 'pilates', 'quiropraxia'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Delivery Frangobom',
		   'descricao' => 'Frango assado, frango crocante à passarinho, costela assada, cupim, joelho de porco, lombo suíno',
		    'endereco' => 'Av. Pe. Anchieta, 2730 - Lojas 01 e 02 - Flórida'.$cidade,
		   'telefones' => '(13)3455-7377',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['frango', 'assado', 'costela', 'cupim', 'joelho', 'porco', 'lombo'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Preuíbe Gás',
		   'descricao' => 'Venda de butijões de gás. Compre pelo whatsapp',
		    'endereco' => "Av. Profª. Therezinha Rodrigues Kalil, 1273 - Park D'aville".$cidade,
		   'telefones' => '0800-772-1180 / 3455-3081 / (whatsapp)99-772-1180',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['gas', 'disk', 'entrega', 'ultragaz'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Turco's Car",
		   'descricao' => 'Funilaria / Pintura / Micro pintura / Fibra',
		    'endereco' => 'Av. Luciano de Bona, 3021 - São João Batista'.$cidade,
		   'telefones' => '(13)99-747-0373',
		'categoria_id' => [],
			'conjunto' => ['funilaria'],
			'palavras' => ['micro', 'parachoque'],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Jovem Arte Gesso e Decoração',
		   'descricao' => 'Trabalhamos com molduras sancas, forros, divisórias, painéis, nichos, sancas abertas e fechadas vários modelos',
		    'endereco' => 'Rua Nossa Senhora do Monte Serrat, 18 - Centro'.$cidade,
		   'telefones' => '(13)98-181-9338 / (13)99-765-9409 / (13)98-838-2274',
		'categoria_id' => '',
			'conjunto' => ['gesso'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Oficina e Guincho Samuel',
		   'descricao' => 'Guincho 24 horas',
		    'endereco' => 'Rua da Estação, 241 - Estação'.$cidade,
		   'telefones' => '(13)99-755-1142',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['guincho', 'reboque'],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Funesp',
		   'descricao' => 'Funesp funerária em Peruibe',
		    'endereco' => 'Av. dos Espedicionários, s/n - Centro'.$cidade,
		   'telefones' => '(13)3455-3985',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['funeraria'],
		        'site' => 'http://www.funespperuibe.com.br',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Gráfica Lider',
		   'descricao' => 'Cartões de visita, envelope, encadernação capa dura, folhinhas, carimbos, panfletos',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)3453-3000',
		'categoria_id' => '',
			'conjunto' => ['grafica'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Santos Imóveis',
		   'descricao' => 'Compra, vende e troca imóveis',
		    'endereco' => 'Rua Quatro, 37 - Loja 1 - Jardim dos Prados'.$cidade,
		   'telefones' => '(13)3455-2789',
		'categoria_id' => '',
			'conjunto' => ['imovel'],
			'palavras' => [],
		        'site' => 'http://www.santosimoveisperuibe.com.br',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'SCI Internet - Fibra Ótica',
		   'descricao' => 'Internet em sua casa ou empresa sem a necessidade de telefone. Internet super rápida. Suporte técnico. Planos de 10Mb e 15Mb',
		    'endereco' => 'Rua Barão de Mauá, 901 - loja 3 - Centro'.$cidade,
		   'telefones' => '(13)3455-3386 / (13)99-778-2780',
		'categoria_id' => '',
			'conjunto' => ['provedor'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Esplendor Imóveis',
		   'descricao' => 'Compra, vende, aluga e administra',
		    'endereco' => 'Av. Pe. Anchieta, 2778 - Lj. 02 - Flórida'.$cidade,
		   'telefones' => '(13)3455-5136 / (13)3455-8993 / (13)99-774-8941 / IDs: 113*2160 / 113*2161',
		'categoria_id' => '',
			'conjunto' => ['imovel'],
			'palavras' => [],
		        'site' => 'http://www.imobiliariaesplendor.com.br',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'On Line Computadores',
		   'descricao' => 'Manutenção e venda de produtos de informática',
		    'endereco' => 'Av. Pe. Anchieta, 1638 - loja 1 (em frente à Telefonica)'.$cidade,
		   'telefones' => '(13) 3453-6331',
		'categoria_id' => '',
			'conjunto' => ['informatica produto', 'informatica manutencao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Del Lanches',
		   'descricao' => 'Lanches de diversos tipos. Pediu chegou.',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)3455-8268 / (13)99-766-6488',
		'categoria_id' => '',
			'conjunto' => ['lanchonete'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Gui Lanches',
		   'descricao' => 'Hanburger frito na hora',
		    'endereco' => "Rua Luiz de Paula, 11 - Parque D'aville".$cidade,
		   'telefones' => '(13)3455-7087',
		'categoria_id' => '',
			'conjunto' => ['lanchonete'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Paulymar Marcenaria',
		   'descricao' => 'Portões, armários, cozinhas, escadas, esquadrias sob medida, madeiramento bruto, e aparelhado, lambril, etc',
		    'endereco' => 'Av. João Abel, 1213 - B. dos Prados'.$cidade,
		   'telefones' => '(13)3456-2674 / 99-722-5194 / 99-657-9677',
		'categoria_id' => '',
			'conjunto' => ['madeira'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Lava Rápido Modelo',
		   'descricao' => 'Lavagem simples, lavagem completa, polimento, troca de óleo, enceramento, cristalização, troca de filtro em geral, sistema leva e traz',
		    'endereco' => 'Av. Vereador Victor Caetano dos Santos, 36 - Jd. Brasil'.$cidade,
		   'telefones' => '(13)99-739-7802 / ID: 921*18659',
		'categoria_id' => '',
			'conjunto' => ['lava rapido'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Açai Lanches',
		   'descricao' => 'Lanches de todos os tipo e para todos os gostos',
		    'endereco' => 'Rua Sete, 115 - Bal. Arpoador'.$cidade,
		   'telefones' => '(13)3455-1290',
		'categoria_id' => '',
			'conjunto' => ['lanchonete'],
			'palavras' => ['acai'],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'DM Materiais para Marcenaria',
		   'descricao' => 'Materiais para marcenaria',
		    'endereco' => 'Av. Luciano de Bona, 4351 - Jd. Belmar II'.$cidade,
		   'telefones' => '(13)3455-5470',
		'categoria_id' => '',
			'conjunto' => ['madeira'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Versátil Marcenaria',
		   'descricao' => 'Serviços de marcenaria em geram. Instalação de divisórias.',
		    'endereco' => 'Rua José Machado, 153 - Estação'.$cidade,
		   'telefones' => '(13)99-630-6881 -> Mário',
		'categoria_id' => '',
			'conjunto' => ['marcenaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],

	[
		        'nome' => 'Ambrosio Baldim Ltda.',
		   'descricao' => 'Comércio de Materiais para Construções',
		    'endereco' => 'Rua Profª Terezinha Rodrigues Kalil, 979 - Jd. Brasil'.$cidade,
		   'telefones' => '(13)3455-1703 / (13)3455-2807',
		'categoria_id' => '',
			'conjunto' => ['construcao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'ArtSul Materiais para Construção',
		   'descricao' => 'Lixeiras, Palitos, Blocos, Jardineiras, Lajes, Escada Caracol, Mourões para ceeca, caixas para ar condicionado',
		    'endereco' => 'Estrada Armando Cunha, 746 - Bairro dos Prados'.$cidade,
		   'telefones' => '(13) 3458-3153 / 3458-4452',
		'categoria_id' => '',
			'conjunto' => ['construcao'],
			'palavras' => ['lixeiras', 'lixeiras', 'palitos', 'palito', 'escada', 'escadas', 'caracol', 'mourao', 'mouroes', 'cerca', 'cercas', 'caixa', 'caixas', 'ar condicionado'],
		        'site' => 'http://www.artsulperuibe.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Júnior Mecânica e Auto Peças',
		   'descricao' => 'Mêcanica, auto peças, auto elétrica, injeção eletrônica',
		    'endereco' => 'Av. 24 de Dezembro, 769 - Estação'.$cidade,
		   'telefones' => '(13) 3455-4849',
		'categoria_id' => '',
			'conjunto' => ['auto pecas'],
			'palavras' => ['eletrica', 'injecao', 'eletronica'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Construcasa Materiais para Construção',
		   'descricao' => 'Tudo para sua construção - Elétrica, hidráulica, ferragens em geral, pisos, metais, louças, sanitários, acabamentos, portas e janelas em ferro e alumínio, areia, pedra, tijolo, areola, cimento, madeira. ENTREGA RÁPIDA!',
		    'endereco' => 'Estrada Armando Cunha, 337 - Vl. Erminda'.$cidade,
		   'telefones' => '(13) 3453-1296',
		'categoria_id' => '',
			'conjunto' => ['construcao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Casa das Pedras Marmoraria',
		   'descricao' => 'Granito e Marmore de vários tipos',
		    'endereco' => 'Av. Luciano de Bona, 3845 - Nova Peruibe'.$cidade,
		   'telefones' => '(13) 3455-2442',
		'categoria_id' => '',
			'conjunto' => ['marmoraria'],
			'palavras' => [],
		        'site' => 'http://casadaspedrasmarmoraria.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Big Big Materiais para construção',
		   'descricao' => 'Materiais para construção novos e usados',
		    'endereco' => 'Av. Tancredo Neves, 905 - Jd. Brasil'.$cidade,
		   'telefones' => '(13) 3455-3608',
		'categoria_id' => '',
			'conjunto' => ['construcao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Marikoota Moda Infantil',
		   'descricao' => 'Tudo em moda infantil.',
		    'endereco' => 'Av. da Costa Grimaldi, 54 - loja 4'.$cidade,
		   'telefones' => '(13) 98-100-3446',
		'categoria_id' => '',
			'conjunto' => ['moda infantil'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Juju Car',
		   'descricao' => 'Mecânico, suspensão, alinhamento, balanceamento, direção, freio, amortecedores, revisão, troca de óleo, limpeza de bico, arrefecimento',
		    'endereco' => 'Av. Pe. Anchieta, 4327 - Nova Peruibe'.$cidade,
		   'telefones' => '(13) 3453-6296 / ID: 126*41994',
		'categoria_id' => '',
			'conjunto' => ['centro automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Van's Car",
		   'descricao' => 'Centro automotivo - elétrica - troca de óleo - suspensão - freio. Mecânica especializada em leves e caminhões / gasolina e alcool / peças para vans em geral ',
		    'endereco' => 'Av. Luciano de Bona, 3355 - Arpoador'.$cidade,
		   'telefones' => '(13) 99-628-8950 / ID: 85*6378 / 35*41*55720',
		'categoria_id' => '',
			'conjunto' => ['centro automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Toda Bella - Moda Intíma e Praia',
		   'descricao' => 'Moda intima e praia',
		    'endereco' => 'Av. Pe. Anchieta, 1511 - Loja 02 - Centro'.$cidade,
		   'telefones' => '(13) 3455-1564',
		'categoria_id' => '',
			'conjunto' => ['moda praia', 'moda intima'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Gilmar Amy's",
		   'descricao' => 'Ambientes planejados',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13) 99-701-9238',
		'categoria_id' => '',
			'conjunto' => ['marcenaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Dj - Motos',
		   'descricao' => 'Oficina - Peças - Acessórios',
		    'endereco' => 'Av. São João, 721 - Centro'.$cidade,
		   'telefones' => '(13)3453-0514 / (13)99-702-2100 (whatsapp)',
		'categoria_id' => '',
			'conjunto' => ['motos'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Pasquel motores',
		   'descricao' => 'Rebobinamento em motores elétricos. Venda de motores novos e recondicionados. Manutenção em motobomba de seguimento bombeiro',
		    'endereco' => 'A. Pe. Anchieta, 3800 - loja 01 - Nova Peruibe'.$cidade,
		   'telefones' => '(13) 3454-1010 / (13)99-752-0981',
		'categoria_id' => '',
			'conjunto' => ['motor eletrico'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Óticas Oliver Express',
		   'descricao' => 'Atendimento especializado, qualidade, rapidez, ótimos preços',
		    'endereco' => 'Praça Monsenhor Lino dos Passos, 130 - Centro'.$cidade,
		   'telefones' => '(13) 3453-3567',
		'categoria_id' => '',
			'conjunto' => ['otica'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Rodrilar Móveis e Colchões',
		   'descricao' => 'Móveis - Beliches - Camas - Colchões - Mesas',
		    'endereco' => 'Av. Pe. Anchieta, 1964 - Stella Maris'.$cidade,
		   'telefones' => '(13) 3454-2006',
		'categoria_id' => '',
			'conjunto' => ['moveis'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Val Móveis',
		   'descricao' => 'Compra e venda de móveis e utensílios',
		    'endereco' => 'Av. Tancredo Neves, 804 - Jd. Brasil'.$cidade,
		   'telefones' => '(13) 99-759-7669',
		'categoria_id' => '',
			'conjunto' => ['moveis'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Padaria Nosso Pão',
		   'descricao' => 'Padaria fica ao lado do Mercado Ponto Bom',
		    'endereco' => 'Av. Luciano de Bona, 2207 - Jd. Ribamar'.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['padaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Padaria do Nei',
		   'descricao' => 'Servimos almoço self service, café da manhã, lanches',
		    'endereco' => 'Av. Pe. Anchieta, 6058 - Balneário Oásis'.$cidade,
		   'telefones' => '(13)3456-2401',
		'categoria_id' => '',
			'conjunto' => ['padaria', 'docinho', 'salgadinho', 'bolo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Bella Paulista',
		   'descricao' => 'Uma panificadora completa. Especialidades do Sul, pães, pães receados, salgados, bolos confeitados, cucas, lanches especiais, chineque',
		    'endereco' => ''.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['padaria', 'bolo', 'docinho', 'salgadinho'],
			'palavras' => ['cucas', 'cuca'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Papelaria Status',
		   'descricao' => 'Tudo em artigos de papelaria',
		    'endereco' => 'Av. 24 de Dezembro, 386 - loja 02 - Estação'.$cidade,
		   'telefones' => '(13) 3454-1085 / 3455-1807',
		'categoria_id' => '',
			'conjunto' => ['papelaria', 'informatica produto', 'impressora insumo', 'impressora marca'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Porto Pet Shop',
		   'descricao' => 'Banho, tosa e veterinária. Medicamentos, taxi dog, roupas, caminhas, acessórios, rações',
		    'endereco' => 'Av. Pe. Anchieta, 4557 - Três Marias'.$cidade,
		   'telefones' => '(13) 3456-1913 / 99-153-9191',
		'categoria_id' => '',
			'conjunto' => ['petshop'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => '4 Patas Pet Shop',
		   'descricao' => 'Rações e Acessórios. Disk ração.',
		    'endereco' => 'Av. Luciano de Bona, 1909 - Vila Romar'.$cidade,
		   'telefones' => '(13) 3455-3619 / (whats) 99-675-8886',
		'categoria_id' => '',
			'conjunto' => ['petshop'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Pesqueiro Girassol',
		   'descricao' => 'Maravilhoso pesqueiro para você passar a tarde com sua família e amigos.',
		    'endereco' => 'Estrada Armando Cunha, Km. 5,8'.$cidade,
		   'telefones' => '(13)3456-1317',
		'categoria_id' => '',
			'conjunto' => ['pesqueiro'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Cristal Piscinas',
		   'descricao' => 'Tudo em produtos para a sua piscina',
		    'endereco' => 'Av. Pe. Anchieta, 4.113'.$cidade,
		   'telefones' => '(13)3455-5823 / (13)3454-1730 / (13)99-722-1185',
		'categoria_id' => '',
			'conjunto' => ['piscina'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Mercado do Piso',
		   'descricao' => 'Materiais para construção, pisos e revestimentos, porcelanato, blocos, lajes a pronta entrega, ferragens prontas sob medida.',
		    'endereco' => 'Rua da Estação, 117 - Estação'.$cidade,
		   'telefones' => '(13)3453-6485',
		'categoria_id' => '',
			'conjunto' => ['construcao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Espaco Novo Calcanhar',
		   'descricao' => 'Podologia',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)3455-8475',
		'categoria_id' => '',
			'conjunto' => ['podologia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Esfiha do Vila',
		   'descricao' => 'Esfirra de vários sabores e tamanho. Consulte nossos pacotes. Fazemos entrega (consulte).',
		    'endereco' => 'Av. Darcy Fonseca, 1156 - Loja 03 - Vila Erminda'.$cidade,
		   'telefones' => '(13) 3456-2776 / (13)99-783-0776',
		'categoria_id' => '',
			'conjunto' => ['esfirraria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Pizza do Vila',
		   'descricao' => 'Saborasas pizzas com valor à partir de R$14,99',
		    'endereco' => 'Av. Darcy Fonseca, 877 - Vila Erminda'.$cidade,
		   'telefones' => '(13)3458-3423 / (13)99-618-1699',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Saldanha's Pizzaria",
		   'descricao' => 'Pizzas de todos os sabores. Realizamos entregas.',
		    'endereco' => 'Av. Pe. Anchieta, 1896 - loja 2'.$cidade,
		   'telefones' => '(13)3454-2020 / (13)99-738-2882',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Chiquinho's Pizzaria",
		   'descricao' => 'De segunda à sexta tem pizza de R$15,00. Fazemos entrega.',
		    'endereco' => 'Rua Tiradentes, 403 - Jd. Ribamar'.$cidade,
		   'telefones' => '(13)3453-2642',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Auto Posto 7 Passos',
		   'descricao' => 'Posto de gasolina',
		    'endereco' => 'Av. João Abel - Bairro dos Prados'.$cidade,
		   'telefones' => '(13)3458-2476',
		'categoria_id' => '',
			'conjunto' => ['posto'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Vargas Peruibe Hotel',
		   'descricao' => 'Hotel em Peruíbe',
		    'endereco' => 'Av. Barão de Mauá, 88 - Centro'.$cidade,
		   'telefones' => '(13)3455-4341 / (13)99-607-8873',
		'categoria_id' => '',
			'conjunto' => ['hotel'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Pousada Porto Aventura",
		   'descricao' => 'Chelés completos com cozinha e suites de luxo',
		    'endereco' => 'Rua 22, 135 - Praia do Guaraú'.$cidade,
		   'telefones' => '(13)3457-9571 / (13)99-746-2794 / (whats) 98-159-2115',
		'categoria_id' => '',
			'conjunto' => ['hotel'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'SJ - Saúde Hospitalar',
		   'descricao' => 'Produtos ortopédicos, cirúrgicos, hospitalares, aparelhos de convalescença',
		    'endereco' => 'Rua Profª Rosa Emília Neves Costa, 130 - Centro'.$cidade,
		   'telefones' => '(13)3453-2525',
		'categoria_id' => '',
			'conjunto' => ['material hospitalar'],
			'palavras' => [],
		        'site' => 'http://sjsaudehospitalar.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Bella Pizza',
		   'descricao' => 'Pizzas de vários sabores. Fazemos entregas.',
		    'endereco' => 'Av. Pe. Anchieta, 7804 - loja 03 - Jd. Icaraíba (Trevo do Ruinas)'.$cidade,
		   'telefones' => '(13)3458-2284 / (13)99-721-9050',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Falcone Pizzaria',
		   'descricao' => 'Pizzaria e almoço por quilo',
		    'endereco' => 'Av. Pe. Anchieta, 1100 - Centro'.$cidade,
		   'telefones' => '(13)3455-1560',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery', 'comida quilo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Primi Piatti',
		   'descricao' => 'Pizzaria com os melhores ingredientes.',
		    'endereco' => 'Av. Pe. Anchieta, 3410 - Bal. Arpoador'.$cidade,
		   'telefones' => '(13)3455-7992 / (13)3453-3649 / (13)99-660-9710',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Perfect Clean Produtos de Limpeza',
		   'descricao' => 'Disk entrega. Produtos para limpeza em geral, descartáveis em geral, vassouras, rodos e esfregões, cestos, baldes e lixeiras',
		    'endereco' => 'Disk Entrega'.$cidade,
		   'telefones' => '(13)3458-5818 / (whats)99-636-6280',
		'categoria_id' => '',
			'conjunto' => ['material limpeza', 'delivery', 'descartavel'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Celeiro do Rei',
		   'descricao' => 'O Empório de Peruibe.',
		    'endereco' => 'Av. Pe. Anchieta, 2681 - Ribamar'.$cidade,
		   'telefones' => '(13)3455-7215',
		'categoria_id' => '',
			'conjunto' => ['emporio'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Oceanu's Quiosque 21",
		   'descricao' => '',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 2350'.$cidade,
		   'telefones' => '(13)99-659-5297',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Pazini's",
		   'descricao' => 'Quiosque na praia',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 1380 - Centro'.$cidade,
		   'telefones' => '(13)3453-4637 / (13)99-709-9486',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Quiosque do Alemão 39',
		   'descricao' => 'Quiosque na praia',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 4824 - Três Marias'.$cidade,
		   'telefones' => '(13)99-739-1112',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Kioski Claudio Japa Peruibe - Kioski 46',
		   'descricao' => 'Aqui você vai saborear as melhores porções',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 6400 - Praia do Oásis'.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Radiadores São Cristóvão',
		   'descricao' => 'Radiadores novos originais com 2 anos de garantia. Solda de alúminio, troca de caixa plática. 25 anos de tradição.',
		    'endereco' => 'Av. Tancredo Neves, 879 - Jd. Brasil'.$cidade,
		   'telefones' => '(13)3455-1686 / (13)99-726-9928',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => ['radiador', 'radiadores', 'manutencao', 'reparo', 'conserto', 'solda', 'aluminio', 'troca', 'caixa', 'plastica', 'novo', 'novos', 'original', 'usado', 'usados'],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Restaurante O Português',
		   'descricao' => 'Pratos típicos da culinária portuguesa',
		    'endereco' => 'Av. Pe. Anchieta, 1815 / 1821 - Stella Maris'.$cidade,
		   'telefones' => '(13)3455-8355',
		'categoria_id' => '',
			'conjunto' => ['restaurante'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Quiosque Deck 27',
		   'descricao' => 'Porções, peixe frito, camarão',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 2870 - Jd. Ribamar'.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Quiosque Jangada 22',
		   'descricao' => 'Porções, peixe frito, camarão',
		    'endereco' => 'Av. Gov. Mário Covas Jr'.$cidade,
		   'telefones' => '(13)3455-6923 / (13)99-650-3154',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Aloha 23',
		   'descricao' => 'Porções, petiscos lanches, batidas, sucos, drinks. Brinquedos / Área de lazer / Shos ao vivo. Venha nos prestigiar em nosso ambiente agradável para você e sua família.',
		    'endereco' => 'Av. Gov. Mário Covas Jr, 2470 - Jangada'.$cidade,
		   'telefones' => '(13)3454-1471 / (whatsapp) (11)94-770-7323',
		'categoria_id' => '',
			'conjunto' => ['quiosque praia'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Toner Games & Informática',
		   'descricao' => 'Loja e asistência técnica para notebooks, computadores e vídeo games',
		    'endereco' => 'Rua Guaporé, 1288 - Stella Maris'.$cidade,
		   'telefones' => '(13) 3455-1074',
		'categoria_id' => '',
			'conjunto' => ['informatica produto', 'informatica manutencao', 'impressora insumo', 'impressora marca'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Eternamento Doce',
		   'descricao' => 'Venha almoçar conosco, servimos almoço de segunda à sexta. Temos também café, doces e salgados',
		    'endereco' => 'Av. São João - Loja 02'.$cidade,
		   'telefones' => '(13)3455-6234 / (13)3455-6229 / (encomendas)(13)99-761-2494',
		'categoria_id' => '',
			'conjunto' => ['docinho', 'salgadinho', 'bolo', 'restaurante'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Tilinha's Restaurante",
		   'descricao' => 'Coma bem e com saúde. Aberto todos os dias à partir das 11:30hs. Um buffet completo para você e sua família!',
		    'endereco' => 'Av. Pe. Anchieta, 909 - Centro'.$cidade,
		   'telefones' => '(13)3454-1892',
		'categoria_id' => '',
			'conjunto' => ['restaurante'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Mex Coxinha',
		   'descricao' => 'Salgado no copo, temos copos de 200, 300, 400 e 700ml. Esperimente também nossos mini churros. Aceitamos encomendas para festas.',
		    'endereco' => 'Av. Darcy Lacerda, 1156 - V. Erminda'.$cidade,
		   'telefones' => '(13)99-673-4449 / (whatsapp)(13)99-708-6589',
		'categoria_id' => '',
			'conjunto' => ['salgadinho'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Sabor de Minas',
		   'descricao' => 'Restaurante e lanchonete. Venha nos conhecer.',
		    'endereco' => 'Rua dos Pescadores, 85 - Loja 5'.$cidade,
		   'telefones' => '(13)99-607-4075',
		'categoria_id' => '',
			'conjunto' => ['restaurante', 'lanchonete'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Primeira Linha Vidros e Esquadrias',
		   'descricao' => 'A 1ª em vidros e esquadrias de alumínio. Box à pronta entrega. Portas e portões, grades e janelas, box temperado, sacadas',
		    'endereco' => 'Av. Luciano de Bona, 5700 - Jd. Oásis'.$cidade,
		   'telefones' => '(13)3453-4086 / vivo: (13)99-644-7616 / nextel: (13)7817-7233 / ID: 99*136543',
		'categoria_id' => '',
			'conjunto' => ['serralheria', 'vidracaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'MetalCosta Serralheria Ltda.',
		   'descricao' => 'Portões automáticos, serralheria em geral, vidraçaria. Atendemos litoral, Vale do Ribeira, Grande São Paulo e Capital',
		    'endereco' => 'Rua Maria Goldin de Moura, 89 - Jd. Itatins'.$cidade,
		   'telefones' => '(13)3455-18737 / (13)99-744-7608',
		'categoria_id' => '',
			'conjunto' => ['serralheria', 'vidracaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => "Serralheria Pinheiro's",
		   'descricao' => 'Esquadrias de alumínio em geral, portas, portões, box, grades, janelas, fechamento vitroux, maxin-ar',
		    'endereco' => 'Av. João Abel, 1217 - Loja 01 - Jd. dos Prados'.$cidade,
		   'telefones' => '(13)3458-2754',
		'categoria_id' => '',
			'conjunto' => ['serralheria', 'vidracaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Agressivos Som e Alarmes',
		   'descricao' => 'Som, alarmes, vidros elétricos, travas elétricas, acessórios em geral',
		    'endereco' => 'Av. Luciano de Bona, 2525 - Jd. Ribamar'.$cidade,
		   'telefones' => '(13)3453-2330',
		'categoria_id' => '',
			'conjunto' => ['som automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Daruba Sonorização Automotiva',
		   'descricao' => 'Som, Insul Film, Alarmes, DVD e Acessórios',
		    'endereco' => 'Av. Pe. Anchieta, 2172 - lj 01'.$cidade,
		   'telefones' => '(13)3453-4562',
		'categoria_id' => '',
			'conjunto' => ['som automotivo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Sorveteria Arcobaleno',
		   'descricao' => 'Sorvetes e pasteis',
		    'endereco' => 'Av. Luciano de Bona, 1721 - Jd. Peruibe'.$cidade,
		   'telefones' => '(13)3455-8042',
		'categoria_id' => '',
			'conjunto' => ['sorveteria', 'pastelaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Disk Latinha',
		   'descricao' => 'Reciclagem para o bem da natureza',
		    'endereco' => 'Av. Tancredo Neves, 755 - Jd. Brasil'.$cidade,
		   'telefones' => '(13)3455-7761',
		'categoria_id' => '',
			'conjunto' => ['reciclagem'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'MZ Supermercados',
		   'descricao' => 'Comércio, açouque e padaria',
		    'endereco' => 'Av. Tancredo Neves, 2566 - Caraguava'.$cidade,
		   'telefones' => '(13)3455-5056 / (13)99-639-8976 / ID: 35*23*40459 / (13)97-410-6831',
		'categoria_id' => '',
			'conjunto' => ['mercado', 'padaria', 'acougue'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Super Mercado Ponto Bom',
		   'descricao' => 'Mercado, padaria, quitanda e açougue',
		    'endereco' => 'Av. Luciano de Bona, 2191 - Jangada'.$cidade,
		   'telefones' => '(13)3453-5576',
		'categoria_id' => '',
			'conjunto' => ['mercado', 'padaria', 'acougue'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Tapeçaria Universo',
		   'descricao' => 'Automotiva, Residencial, Náutica, Tudo em couro automotivo, bancos, volantes e todo tipo de acessório em couro.',
		    'endereco' => 'Rua da Estação, 345 - Estação'.$cidade,
		   'telefones' => '(13)3507-2433 / (13)99-785-9556 / (13)97-401-5882 / ID:35*18*36959',
		'categoria_id' => '',
			'conjunto' => ['tapecaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Tapeçaria Silva',
		   'descricao' => 'Reforma de estofados automotivos e residenciais. Reforma de banco de moto.',
		    'endereco' => 'Praça 15 de Novembro, 36 - Ribamar'.$cidade,
		   'telefones' => 'whatsapp: (13)99-738-2912',
		'categoria_id' => '',
			'conjunto' => ['tapecaria'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Toldos Martins',
		   'descricao' => 'Toldos, luminosos, fachadas, policarbonato, letreiros, impressão digital, grafica express. Fazemos serviços de serralheria e vidraçaria.',
		    'endereco' => "Rua Santos Dumont, 44 - Centro ".$cidade,
		   'telefones' => '(13)3454-2388 / (13)3455-9731 / (13)99-715-6162',
		'categoria_id' => '',
			'conjunto' => ['serralheria', 'vidracaria', 'toldo'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Grafitex - Indústria e Comércio',
		   'descricao' => 'Revestimentos. Massa corrida PVC e acrílica, niveladora, tinta acrílica, textura e grafiato coloridos',
		    'endereco' => 'Av. Pe. Anchieta, 3800 - Loja 01 - Nova Peruíbe'.$cidade,
		   'telefones' => '(13)3454-2358 / (13)99-707-9595 / (13)98-127-6564',
		'categoria_id' => '',
			'conjunto' => ['revestimento produto'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'GJR Veículos',
		   'descricao' => 'Compra, vende, troca, financia, consignação.',
		    'endereco' => ''.$cidade,
		   'telefones' => '(13)3455-3107',
		'categoria_id' => '',
			'conjunto' => ['veiculo comercializacao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Plana Solo',
		   'descricao' => 'Terraplanagem e locação de equipamentos. Limpeza e nivelamento de terrenos, arerro, areia, pedra e derivados. Demolição e remoção de entulhos, escavação de piscinas e tanques.',
		    'endereco' => 'Rua Marília, 1642'.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['terraplanagem'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Dutchello Pizzas',
		   'descricao' => '30 Sabores de Pizza por R$14,99 cada. Ligue e peça a sua',
		    'endereco' => ''.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => ['pizzaria', 'delivery'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Novo Móveis Planejados',
		   'descricao' => 'Mais de 20 anos em Períbe, móveis planejados. Kássia Sodré',
		    'endereco' => 'Av. Pe. Anchieta, 3100'.$cidade,
		   'telefones' => '(13)3455-1500 / (13)98-880-8560',
		'categoria_id' => '',
			'conjunto' => ['moveis'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Automaton',
		   'descricao' => 'Construção com qualidade e preço baixo',
		    'endereco' => 'Av. Pe. Anchieta, 9932 - Convento Velho'.$cidade,
		   'telefones' => '(13)3458-3635',
		'categoria_id' => '',
			'conjunto' => ['construcao', 'ferragem'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	
	[
		        'nome' => 'Bella Vita',
		   'descricao' => 'Farmácia de manipulação. Manipulação de fórmulas, produtos naturais, homeopatia',
		    'endereco' => 'Rua Prof. Rosa Emília Neves Costa, 213 - Centro'.$cidade,
		   'telefones' => '(13)3455-5048 / (13)3455-9152',
		'categoria_id' => '',
			'conjunto' => ['farmacia manipulacao'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Vita Oficina de Jóias',
		   'descricao' => 'Avaliamos e copramos jóias',
		    'endereco' => 'Av. 24 Dezembro, 597 - Sala 12 - Estação'.$cidade,
		   'telefones' => '(13)99-618-0561 / (13)99-749-3786 / (13)99-163-9090',
		'categoria_id' => '',
			'conjunto' => ['joia oficina', 'joia venda'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Conita Contabilidade',
		   'descricao' => 'Abertura de firma, imposto de renda, escrit. fiscal',
		    'endereco' => 'Av. Pe. Anchieta, 1461 - Sala 05 - Centro'.$cidade,
		   'telefones' => '(13) 3455-5892',
		'categoria_id' => '',
			'conjunto' => ['contabilidade'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'Trevisã - Monitoramento 24 Horas',
		   'descricao' => 'Alarmes, CFTV, cerca elétrica',
		    'endereco' => 'Av. Pe. Anchieta, 2452 - Jd. Ribamar'.$cidade,
		   'telefones' => '(13)3453-1467',
		'categoria_id' => '',
			'conjunto' => ['seguranca'],
			'palavras' => [],
		        'site' => 'http://www.trevisamonitoramento.com.br',
		  'prioridade' => '5',
	],
	[
		        'nome' => 'TAC - Tessari Assessoria & Consultoria',
		   'descricao' => 'Seu veículo está com prestação atrasada e você não tem mais como pagar??? Nós te pagaremos um ótimo preço à vista e quitamos seu financiamento veicular. Nos responsabilizamos pela quitação do seu veículo, registrado em cartório.',
		    'endereco' => 'Av. João Bechir, 69 - Sala 04 - Estação'.$cidade,
		   'telefones' => '(13) 99-712-8022 / (13) 98-1263509',
		'categoria_id' => '',
			'conjunto' => ['financiamento veicular'],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	/*
	[
		        'nome' => '',
		   'descricao' => '',
		    'endereco' => ''.$cidade,
		   'telefones' => '',
		'categoria_id' => '',
			'conjunto' => [],
			'palavras' => [],
		        'site' => '',
		  'prioridade' => '5',
	],
	*/
];

return $anunciantesPeruibe;
